version: '2.1'

services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  server_test:
    build:
      context: server
      dockerfile: Dockerfile.testing
    volumes:
      - ./server:/app

  server_deploy:
    build:
      context: server
      dockerfile: Dockerfile.deploy
    volumes:
      - ./server:/app
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      CLOUDSDK_CORE_PROJECT: gumo-example
    # command: gcloud app deploy src/app.yaml
