version: '2.4'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  server_test:
    build:
      context: server
      dockerfile: Dockerfile.testing
    volumes:
      - ./server:/app
