version: '2.1'

services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    environment:
      SERVER_PORT: 8080
      DATASTORE_EMULATOR_HOST: datastore_emulator:8081
      GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/service-account-development.json"
      USE_TASK_EMULATOR: "true"
    depends_on:
      - datastore_emulator
    ports:
      - "8080:8080"

  server_test:
    build:
      context: server
      dockerfile: Dockerfile.testing
    volumes:
      - ./server:/app
    environment:
      PYTEST: "true"
      DATASTORE_EMULATOR_HOST: datastore_emulator_test:8082
      GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/service-account-development.json"
      USE_TASK_EMULATOR: "true"
    links:
      - datastore_emulator_test

  server_deploy:
    build:
      context: server
      dockerfile: Dockerfile.deploy
    volumes:
      - ./server:/app
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      CLOUDSDK_CORE_PROJECT: gumo-example
    # command: gcloud app deploy src/app.yaml

  datastore_emulator:
    image: singularities/datastore-emulator
    volumes:
      - datastore-emulator-storage:/opt/data
    environment:
      DATASTORE_PROJECT_ID: gumo-example
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
    ports:
      - "8081:8081"

  datastore_emulator_test:
    image: singularities/datastore-emulator
    volumes:
      - datastore-emulator-storage:/opt/data
    environment:
      DATASTORE_PROJECT_ID: gumo-example
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8082
    ports:
      - "8082:8082"
    command: --no-store-on-disk --consistency=1

  datastore_ui:
    build:
      context: server/tools/datastore_ui
    environment:
      PORT: "8000"
    depends_on:
      - datastore_emulator
      - datastore_emulator_test
    ports:
      - "8000:8000"

  task_emulator:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    environment:
      SERVER_HOST: server
      SERVER_PORT: 8080
      TASK_EMULATOR_PORT: 8083
      DATASTORE_EMULATOR_HOST: datastore_emulator:8081
      GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/service-account-development.json"
      USE_TASK_EMULATOR: "true"
    depends_on:
      - server
      - redis
    ports:
      - "8083:8083"
    command: python src/task_emulator_server.py

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  datastore-emulator-storage:
    driver: local
