version: 2.1

jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: create credential file
          command: |
            mkdir -p server/credentials
            rm -f server/credentials/service-account-development.json
            echo $GCP_CREDENTIALS_GUMO_EXAMPLE_f78f2998a6a0 > server/credentials/service-account-development.json

      - run:
          name: server_test
          command: docker-compose run --rm server_test
